# Only this config file should be updated monthly and not the scripts except\
# absolutely necessary

# Change the following when running in your virtual env.
input_data: "./data/"


# these don't need changing
uk_weather_data: "uk_weather.csv"
germany_weather_data: "germany_weather.csv"
netherlands_weather_data: "netherlands_weather.csv"

api_key: "bc2d732248597a8725c1f5d51e5d3e8a"